### ISSUE TITLE
[design] Non-polling model?

### ISSUE THREAD

**Issue by xyntrix** [jenkins-x/jx-git-operator#73]
In some situations a direct polling model may introduce challenges (such as rate limiting across a busy single organization). Is there an opinion on the design path for adding a different work-trigger method or even abstracting the current polling method?

For instance, if I wanted to develop a push model receiver or a queue driven workflow is that in line with the design intent here or would that go better into a separate operator (ex: jx-webhook-operator, jx-kafka-operator, etc..)?

**Comment by jstrachan** [comment]
the main reason we've not done a push model so far is to reduce the footprint of the git operator when using it in staging/pre-production/production clusters. e.g. to avoid needing to include Tekton or setup Ingress / Webhooks etc.

We should be able to add a `jx admin boot` or something like that - to effectively run the boot job whenever you like so if you know you want to run a boot job to just trigger it.

You can also configure the polling period to tone it right down if you are hitting rate limits. 

BTW rate limits usually relate to git API calls rather than git pulls? e.g. we've never seen any git pull rate limits yet with github.com
